App_Login/urls.py
from django.urls import path
from App_Login.views import *

app_name = 'App_Login'

urlpatterns = [
    path('signup/', signup_system, name='signup'),
    path('faculty-signup/', faculty_signup, name='faculty-signup'),
    path('login/', login_system, name='login'),
    path('logout/', logout_system, name='logout'),
]

Online_Attendance_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Attendance.urls')),
    path('accounts/', include('App_Login.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),
    path('reset-password-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset-password-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Faculty(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='faculty')
    phone = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(upload_to='Faculty_image', null=True, blank=True)

    def __str__(self):
        return str(self.user.username)


def student_directory_path(instance, filename):
    name, ext = filename.split(".")
    name = instance.class_id  # + "_" + instance.department + "_" + instance.batch + "_" + instance.section
    filename = name + '.' + ext
    return 'Student_Images/{}/{}/{}/{}'.format(instance.department, instance.batch, instance.section, filename)


# Department ++ Section ++ Course
class Department(models.Model):
    department = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.department}"


class Batch(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='department_in_semester')
    Batch = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.department} {self.Batch}"


class Course(models.Model):
    Batch = models.ForeignKey(Batch, on_delete=models.CASCADE, related_name='semester_in_courses')
    course_code = models.CharField(max_length=255)
    course = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.course_code}-{self.course}"


SECTION = (
    ('A', 'A'),
    ('B', 'B'),
    ('C', 'C'),
    ('D', 'D'),
    ('E', 'E'),
    ('F', 'F'),
    ('G', 'G'),
)
# End


class Student(models.Model):
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    class_id = models.CharField(max_length=200, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='department_name')
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE, related_name='Batch_name')
    section = models.CharField(max_length=100, null=True, choices=SECTION)
    profile_pic = models.ImageField(upload_to=student_directory_path, null=True, blank=True)

    def __str__(self):
        return str(self.class_id)

App_Login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from App_Login.models import *


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class FacultyForm(forms.ModelForm):
    class Meta:
        model = Faculty
        exclude = ['user']

App_Login/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from App_Login.forms import SignUpForm, CreateStudentForm, FacultyForm


# Create your views here.
def signup_system(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            passwd = form.cleaned_data.get('password1')
            this_user = authenticate(username=username, password=passwd)
            if this_user is not None:
                login(request, this_user)
                return HttpResponseRedirect(reverse('App_Login:faculty-signup'))
    return render(request, 'App_Login/signup.html', context={'form': form})


@login_required
def faculty_signup(request):
    form = FacultyForm()
    if request.method == 'POST':
        form = FacultyForm(request.POST, request.FILES)
        if form.is_valid():
            faculty_form = form.save(commit=False)
            faculty_form.user = request.user
            faculty_form.save()
            return HttpResponseRedirect(reverse('App_Login:login'))
    return render(request, 'App_Login/facultyForm.html', context={'form': form})


def login_system(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user=user)
                return HttpResponseRedirect(reverse('App_Attendance:Home'))
    return render(request, 'App_Login/login-form.html', context={'form': form})


def logout_system(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))

templates/App_Login/facultyForm.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_filters %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Faculty Setup</title>
    <style type="text/css">
        .form-div {
            margin-top: 10%;
            padding: 10px;
            -webkit-box-shadow: 0 0 10px #cccccc;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 p-5 form-div">
            <form method="post" class="form-group" enctype="multipart/form-data">
                {% csrf_token %}
                <legend class="form-group">
                    Faculty Setup
                </legend>
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group pt-3">
                    <input type="submit" class="btn btn-primary">
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_Login/login-form.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_filters %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Signup</title>
    <style type="text/css">
        .about-us {
            padding: 10px;
            margin-top: 10%;
            text-align: center;
        }

        .about-us h1 {
            font-weight: 700;
            font-size: 30px;
            color: #00ffff;
        }

        .about-us p b a {
            text-decoration: none;
            color: brown;
        }

        .form-div {
            margin-top: 10%;
            padding: 10px;
            -webkit-box-shadow: 0 0 10px #cccccc;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-5 p-5 about-us">
            <h1>Online Attendance System</h1>
            <p>
                This website is created by
                <b><a href="#">Maloy Baroi Virat</a></b> &
                <b><a href="#">Evana Perveen Eva</a></b>
            </p>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-6 p-5 form-div">
            <form method="post" class="form-group">
                {% csrf_token %}
                <legend class="form-group">
                    Signup Form
                </legend>
                <fieldset class="form-group">
                    {{ form|crispy }}
                    <input type="checkbox" onclick="passToText()" id="password-show">
                    <label for="password-show">see password</label>
                </fieldset>
                <div class="form-group pt-3" style="text-align: center;">
                    <a href="{% url 'password_reset' %}" style="text-decoration: none; color: red; float: left">
                        Forget Password?
                    </a>
                    <input type="submit" class="btn btn-primary" style="float: right">
                </div>
            </form>
            <br>
            <hr>
            <div style="text-align: center">
                <a href="{% url 'App_Login:signup' %}" type="button" class="btn btn-success" >Signup As Faculty</a>
            </div>
        </div>
    </div>
</div>
<!---- JavaScript ---->
<script type="text/javascript">
    let pass = document.getElementById('id_password');
    pass.type = 'password';

    function passToText() {
        if (pass.type === 'password') {
            pass.type = 'text';
        } else {
            pass.type = 'password';
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_Login/signup.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    {% load crispy_forms_filters %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Signup</title>
    <style type="text/css">
        .form-div {
            margin: 5% 0 5% 0;
            padding: 30px;
            border-radius: 5px;
            -webkit-box-shadow: 0 0 10px #cccccc;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 form-div">
            <form method="post" class="form-group">
                {% csrf_token %}
                <legend class="form-group">
                    Signup Form
                </legend>
                <fieldset class="form-group">
                    {{ form|crispy }}
                    <input type="checkbox" onclick="passToText()" id="password-show">
                    <label for="password-show">see password</label>
                </fieldset>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary">
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

<!---- JavaScript ---->
<script type="text/javascript">
    let pass1 = document.getElementById('id_password1');
    let pass2 = document.getElementById('id_password2');
    pass1.type = 'password';
    pass2.type = 'password';

    function passToText() {
        if (pass1.type === 'password') {
            pass1.type = 'text';
            pass2.type = 'text';
        } else {
            pass1.type = 'password';
            pass2.type = 'password';
        }
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>
</html>